### ISSUE TITLE
Pipelines not registering

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/glTF#2]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
After following the guide to setup the Pipelines, they are not being recognised in PR's

Thoughts @StephenHodgson ?

**Comment by FejZa** [comment]
What do you mean they are not being recongized in PRs? For a pipeline to be available as an status check it needs to run at least once. Then it can be setup as a status check in the branch policies.

**Comment by FejZa** [comment]
Pipelines are now available for status check config. But this project does not build currently.

**Comment by SimonDarksideJ** [comment]
Figured out why it's not building yet. Still waiting for the Core release to update which extracts the functionality, so it's conflicting.

**Comment by StephenHodgson** [comment]
I'll check it out and see what's going on

**Comment by SimonDarksideJ** [comment]
Dino checked and says it's because it doesn't currently build.  Not sure why, checking

**Comment by StephenHodgson** [comment]
Pipelines seem to be running fine last I checked. There's a script compiler error bc of the breaking changes in core required before the pipeline can pass
